### ISSUE TITLE
Is global variable 'regexp' necessary ?

### ISSUE THREAD

**Issue by syohex** [myuhe/color-moccur.el#2]
https://github.com/myuhe/color-moccur.el/blob/master/color-moccur.el#L805

`color-moccur`をロードした状態で `lexical-bindings`が有効かつ
 `regexp`という名前のローカル変数が使われているパッケージ(`anzu`等)を
バイトコンパイルしてロードすると挙動がおかしくなります.
(Emacs本体にも問題があるのではないかと思うのですが,)
不要ならば削除, 必要ならば `moccur-regexp`みたいにしていただけない
でしょうか ?

よろしくお願いします.

**Comment by myuhe** [comment]
不要そうだったので削除しときました！

**Comment by syohex** [comment]
ありがとうございます.
