### ISSUE TITLE
excess pace in (moccur-search -line regexp)?

### ISSUE THREAD

**Issue by kaz-yos** [myuhe/color-moccur.el#3]
The 20140424 version gives an error when doing moccur-grep there is no "-line" or something similar to that.

" -line" appears here, and it is a change introduced in the 20140424 version.
https://github.com/myuhe/color-moccur.el/blob/master/color-moccur.el#L1423

I believe there should be no space between moccur-search and -line.
- NEW    (while (moccur-search -line regexp)
- CORRECT?    (while (moccur-search-line regexp)

The latter made moccur-grep functional again. Thanks you so much for maintaining this extremely useful package!

**Comment by myuhe** [comment]
I messed it up. Thanks!!
